name: Run Check

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ARCH: x86_64
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with:
          pattern: "!*.dockerbuild"
      - uses: azure/setup-kubectl@v5
      - uses: fermyon/actions/spin/setup@v1
        with:
          version: "v2.7.0"

      - name: Setup build env
        run: |
          make setup

      - name: Extract containerd-shim-spin-linux-${{ env.ARCH }}
        run: |
          mkdir -p ./bin
          for f in containerd-shim-spin-*-linux-${{ env.ARCH }}/containerd-shim-spin-*-linux-${{ env.ARCH }}.tar.gz
            do tar -xzf "$f" -C ./bin
          done

      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.31.0/kind-linux-amd64
          chmod +x ./kind
          mv ./kind /usr/local/bin/kind
      
      - name: Install wkg
        run: make install-wkg

      - name: Run integration tests
        run: BIN_DIR="./bin" IS_CI=true make integration-tests

      - name: Collect debug logs
        if: failure()
        run: make tests/collect-debug-logs
 
      - name: Upload debug logs
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: debug-logs
          path: debug-logs/
          retention-days: 5

      - name: Output runner storage on failure
        if: failure()
        run: df -h

      - name: Clean up kind
        if: always()
        run: make tests/clean
